//USER REGISTRATION //POST
export const USER_REGISTRATION_REQUEST='USER_REGISTRATION_REQUEST'
export const USER_REGISTRATION_SUCCESS='USER_REGISTRATION_SUCCESS'
export const USER_REGISTRATION_ERROR='USER_REGISTRATION_ERROR'

//USER LOGIN //GET
export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS= 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR= 'USER_LOGIN_ERROR'

//POST BARANG
export const POST_ITEMS_REQUEST = 'POST_ITEMS_REQUEST'
export const POST_ITEMS_SUCCESS= 'POST_ITEMS_SUCCESS'
export const POST_ITEMS_ERROR= 'POST_ITEMS_ERROR'

//GET BARANG
export const GET_BARANG_REQUEST= 'GET_BARANG_REQUEST'
export const GET_BARANG_SUCCESS= 'GET_BARANG_SUCCESS'
export const GET_BARANG_ERROR= 'GET_BARANG_ERROR'

//GET BARANG BY ID
export const GET_ITEMS_ID_REQUEST= 'GET_ITEMS_ID_REQUEST'
export const GET_ITEMS_ID_SUCCESS= 'GET_ITEMS_ID_SUCCESS'
export const GET_ITEMS_ID_ERROR= 'GET_ITEMS_ID_ERROR'

//DELETE BARANG
export const DELETE_BARANG_REQUEST = 'DELETE_BARANG_REQUEST'
export const DELETE_BARANG_SUCCESS = 'DELETE_BARANG_SUCCESS'
export const DELETE_BARANG_ERROR = 'DELETE_BARANG_ERROR'

//belajar
export const tambah= 'tambah'
export const kurang= 'kurang'

//CEK USER LOGIN
export const USER_IS_LOGIN = 'USER_IS_LOGIN'
export const USER_IS_LOGOUT = 'USER_IS_LOGOUT'